name: 'Miqa Test Kickoff'
description: 'Kick off jobs on Miqa and status checks in GitHub'
inputs:
  INSTALLATION_ID:
    description: 'App Installation ID for the miqa-status-check Github App'
    required: true
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  TRIGGER_ID:
    description: 'Miqa test trigger ID'
    required: true
  DOCKER_URI:
    description: 'Docker URI for version to test on'
    required: true
  MIQA_ENDPOINT:
    description: 'Root URL for Miqa (proxy or app domain)'
    required: true
  CHECK_NAME:
    description: 'Name to display in checks status'
    default: 'Triggered Miqa Test'
  SHA:
    description: 'github.sha'
  REPOSITORY:
    description: 'github.repository'
  COMPONENT_IDS:
    description: 'Specific component IDs to update (if docker is not registered to component watchers)'
    required: false
    default: ''
  ADDITIONAL_INSTRUCTIONS:
    description: 'Additional custom instructions to pass as query parameters to the trigger. Prefix with &.'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
      - name: HTTP Request - Create Check Run
        uses: fjogeleit/http-request-action@v1.11.0
        id: trigger_1
        with:
          url: 'http://miqa-github.herokuapp.com/create_check_manual'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"installation_id":"${{inputs.INSTALLATION_ID}}","repository_full_name":"${{ github.repository }}", "head_sha":"${{ github.sha  }}", "check_name":"${{inputs.CHECK_NAME}}"}'
      - name: Set Check Run ID
        run: echo  "CHECK_RUN_ID=${{ fromJSON(fromJSON(toJSON(steps.trigger_1.outputs.response))).id }}" >> $GITHUB_ENV
      - name: HTTP Request - Miqa Trigger
        uses: fjogeleit/http-request-action@v1.11.0
        with:
          url: '${{ inputs.MIQA_ENDPOINT }}/trigger_test_auto/${{ inputs.TRIGGER_ID }}?app=gh&uri=${{ inputs.DOCKER_URI }}&allow_override=1&event_id=${{ env.CHECK_RUN_ID }}&repo=${{ inputs.REPOSITORY }}&commit=${{ inputs.SHA }}&specific_components=${{ inputs.COMPONENT_IDS }}${{ inputs.ADDITIONAL_INSTRUCTIONS }}'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"repo":"${{ inputs.REPOSITORY }}", "commit":"${{ inputs.SHA }}"}'
